# Generated by Django 4.2.2 on 2023-06-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(default='0802', max_length=20),
        ),
    ]
