# Generated by Django 4.2.2 on 2023-06-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_admin_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin',
            new_name='user',
        ),
    ]
