# Generated by Django 4.2.1 on 2023-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_std_class_subject_teacher_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.CharField(default='Default address', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Default address', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='Default address', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
    ]
