# Generated by Django 4.2.1 on 2023-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_admin_address_admin_email_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_class',
            name='subject',
            field=models.ManyToManyField(related_name='subject', to='panel.subject'),
        ),
    ]
