# Generated by Django 4.2.1 on 2023-06-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_std_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_taken',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject_taught', to='panel.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='optional_subjects',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='optional_subject', to='panel.optionalsubject'),
        ),
    ]
