# Generated by Django 4.2.1 on 2023-06-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_optionalsubject_teacher_subject_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_clas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.std_class'),
        ),
    ]
