# Generated by Django 4.2.1 on 2023-06-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_student_std_clas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
