# Generated by Django 4.2.2 on 2023-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_remove_admin_email_remove_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='optional_subjects',
        ),
        migrations.AddField(
            model_name='std_class',
            name='optional_subject',
            field=models.ManyToManyField(related_name='subject', to='panel.optionalsubject'),
        ),
    ]
