# Generated by Django 4.2.2 on 2023-06-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_remove_student_optional_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('optional_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.optionalsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.subject')),
            ],
        ),
    ]
