# Generated by Django 4.2.2 on 2023-06-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalSubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
