# Generated by Django 4.2.2 on 2023-06-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_optionalsubjectscore_subjectscore_delete_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_taken',
        ),
        migrations.AddField(
            model_name='optionalsubject',
            name='Teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.teacher'),
        ),
        migrations.CreateModel(
            name='StdClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('class_teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.teacher')),
                ('optional_subject', models.ManyToManyField(related_name='optional_subject', to='panel.optionalsubject')),
                ('subject', models.ManyToManyField(related_name='subject', to='panel.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='std_clas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.stdclass'),
        ),
        migrations.DeleteModel(
            name='std_class',
        ),
    ]
