# Generated by Django 4.2.2 on 2023-06-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_remove_teacher_subject_taken_optionalsubject_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionalsubjectscore',
            old_name='Score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_clas',
            new_name='std_class',
        ),
    ]
