# Generated by Django 4.2.2 on 2023-06-24 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_rename_score_optionalsubjectscore_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalsubject',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='optional_subject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher', to='panel.optionalsubject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_subject_teacher', to='panel.subject'),
        ),
    ]
