# Generated by Django 4.2.2 on 2023-06-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_remove_optionalsubject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdclass',
            name='optional_subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='optional_subject', to='panel.optionalsubject'),
        ),
    ]
