# Generated by Django 4.2.2 on 2023-06-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_alter_stdclass_optional_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='optional_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher', to='panel.optionalsubject'),
        ),
    ]
