# Generated by Django 4.2.2 on 2023-06-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_alter_teacher_optional_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='optional_subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_taken',
        ),
        migrations.AddField(
            model_name='optionalsubject',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_subject_taught', to='panel.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_taught', to='panel.teacher'),
        ),
    ]
