# Generated by Django 4.2.2 on 2023-06-26 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_remove_teacher_optional_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='optional_subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='YYYY-MM-DD HH:MM:SS', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='2023-06-25 18:00:00', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stdclass',
            name='optional_subject',
            field=models.ManyToManyField(blank=True, related_name='optional_subject', to='panel.optionalsubject'),
        ),
    ]
