# Generated by Django 4.2.2 on 2023-06-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_student_dob_student_level_student_optional_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='optional_subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='optional_subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='panel.optionalsubject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, limit_choices_to={'subject__lte': 8}, related_name='students', to='panel.subject'),
        ),
        migrations.RemoveField(
            model_name='optionalsubject',
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='stdclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.teacher'),
        ),
        migrations.AlterField(
            model_name='stdclass',
            name='optional_subject',
            field=models.ManyToManyField(blank=True, related_name='classes', to='panel.optionalsubject'),
        ),
        migrations.AlterField(
            model_name='stdclass',
            name='subject',
            field=models.ManyToManyField(related_name='classes', to='panel.subject'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='+234-', max_length=20),
        ),
        migrations.AddField(
            model_name='optionalsubject',
            name='Teacher',
            field=models.ManyToManyField(related_name='optional_subject_taught', to='panel.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Teacher',
            field=models.ManyToManyField(related_name='subject_taught', to='panel.teacher'),
        ),
    ]
